### ISSUE TITLE
Неверные изображения

### ISSUE THREAD

**Issue by ndikanov** [Starkovden/Documenting_APIs#11]
На некоторых страницах неверные изображения:
1. https://github.com/docops-hq/learnapidoc-ru/blob/master/like-developer/submit-requests-postman.md ([оригинал](https://idratherbewriting.com/learnapidoc/docapis_postman.html))
    - https://github.com/docops-hq/learnapidoc-ru/raw/master/like-developer/pics/3.png -> https://idratherbewritingmedia.com/images/api/postmanopenweatherapi.png
    - https://github.com/docops-hq/learnapidoc-ru/raw/master/like-developer/pics/4.png -> https://idratherbewritingmedia.com/images/api/postmanopenweatherapiresponse.png
    - https://github.com/docops-hq/learnapidoc-ru/raw/master/like-developer/pics/5.png -> https://idratherbewritingmedia.com/images/api/postmancollectiondialog.png
2. https://github.com/docops-hq/learnapidoc-ru/blob/master/like-developer/inspect-json.md ([оригинал](https://idratherbewriting.com/learnapidoc/docapis_json_console.html))
    - https://github.com/docops-hq/learnapidoc-ru/raw/master/like-developer/pics/7.png -> https://idratherbewritingmedia.com/images/api/postmanjqueryajax.png

**Comment by Starkovden** [comment]
Спасибо большое! 
Поправил
